import {FormEvent, useEffect, useMemo, useRef, useState} from 'react';
import {api, calculateMultiBilling, createDomainBilling, domainCustomers, createDomainCustomer, domainItems, headerGoldRates, salePdf, sendInvoiceWhatsApp} from '../api';
import './Billing.css';
import BarcodeCameraScanner from './BarcodeCameraScanner';

type Line={
 id:string; jewelleryItemId:string; name:string; design:string; tag:string; barcode:string; purity:string;
 grossWeight:number; stoneWeight:number; netWeight:number; goldRate:number; wastagePercent:number;
 makingCharge:number; stoneCharge:number; otherCharge:number;
};

const emptyLine=(x:any, rate:number):Line=>({
 id:String(x.id), jewelleryItemId:String(x.id), name:x?.product?.name||'Jewellery', design:x?.product?.design?.name||'',
 tag:x?.tag?.tagNo||'', barcode:x?.tag?.barcode||'', purity:x?.purity?.name||x?.purity?.karat||'',
 grossWeight:Number(x?.grossWeight||0), stoneWeight:Number(x?.stoneWeight||0), netWeight:Number(x?.netWeight ?? Math.max(Number(x?.grossWeight||0)-Number(x?.stoneWeight||0),0)),
 goldRate:Number(rate||0), wastagePercent:Number(x?.wastagePercent||0), makingCharge:Number(x?.makingCharge||0), stoneCharge:Number(x?.stoneValue||0), otherCharge:0
});

export default function BillingModule({ready,onNotice}:{ready:boolean;onNotice:(x:string)=>void}){
 const [customers,setCustomers]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[lines,setLines]=useState<Line[]>([]);
 const initialBillingDate = new Date();
 const [f,setF]=useState<any>({invoiceNo:`INV-${Date.now()}`,saleDate:initialBillingDate.toISOString().slice(0,10),saleTime:initialBillingDate.toTimeString().slice(0,5),customerId:'',goldRate:0,gstPercent:3,discount:0,paymentMode:'CASH',paymentAmount:0});
 const [calc,setCalc]=useState<any>(null),[lastCreated,setLastCreated]=useState<any>(null),[barcode,setBarcode]=useState(''),[scanBusy,setScanBusy]=useState(false),[cameraOpen,setCameraOpen]=useState(false),[marketRates,setMarketRates]=useState<any[]>([]);
 const [itemSearch,setItemSearch]=useState(''),[itemOpen,setItemOpen]=useState(false),[customerSearch,setCustomerSearch]=useState(''),[customerOpen,setCustomerOpen]=useState(false);
 const [newCustomerMode,setNewCustomerMode]=useState(false),[newCustomer,setNewCustomer]=useState<any>({name:'',phone:'',email:'',gstin:'',address:''}),[customerSaving,setCustomerSaving]=useState(false);
 const barcodeRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{
   if(!ready){setCustomers([]);setItems([]);setMarketRates([]);return;}
   Promise.all([domainCustomers(),domainItems(),headerGoldRates()]).then(([c,i,m])=>{
     setCustomers(Array.isArray(c.data)?c.data:[]);setItems(Array.isArray(i.data)?i.data:[]);
     const rates=Array.isArray(m.data?.marketRates)&&m.data.marketRates.length?m.data.marketRates:(Array.isArray(m.data?.rates)?m.data.rates:[]);setMarketRates(rates);const r22=rates.find((x:any)=>String(x.karat??x.purity??'').replace(/[^0-9]/g,'')==='22');if(Number(r22?.ratePerGram)>0)setF((v:any)=>Number(v.goldRate||0)>0?v:{...v,goldRate:Number(r22.ratePerGram)});
   }).catch(e=>onNotice(e?.response?.data?.message||'Unable to load billing masters'));
 },[ready]);
 useEffect(()=>{if(ready)window.setTimeout(()=>barcodeRef.current?.focus(),150);},[ready]);
 const update=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));
 const selectedCustomer=customers.find(x=>String(x.id)===String(f.customerId));
 const filteredCustomers=useMemo(()=>{const q=customerSearch.trim().toLowerCase();const src=customers.filter(x=>x.active!==false);return (q?src.filter(x=>[x?.name,x?.phone,x?.email,x?.gstin,x?.address].filter(Boolean).join(' ').toLowerCase().includes(q)):src).slice(0,80);},[customers,customerSearch]);
 const availableItems=useMemo(()=>items.filter(x=>x.status==='IN_STOCK'&&!lines.some(l=>String(l.jewelleryItemId)===String(x.id))),[items,lines]);
 const filteredItems=useMemo(()=>{const q=itemSearch.trim().toLowerCase();const src=availableItems;if(!q)return src.slice(0,80);return src.filter(x=>[x?.product?.name,x?.product?.sku,x?.product?.design?.name,x?.tag?.tagNo,x?.tag?.barcode,x?.huid,x?.purity?.name,x?.purity?.karat].filter(Boolean).join(' ').toLowerCase().includes(q)).slice(0,80);},[availableItems,itemSearch]);
 const rateForPurity=(purity:any)=>{const key=String(purity?.karat??purity?.name??purity??'').toUpperCase().replace(/[^0-9]/g,'');const found=marketRates.find(x=>String(x.karat??x.purity??'').toUpperCase().replace(/[^0-9]/g,'')===key);return Number(found?.ratePerGram||0);};
 const addItem=(x:any)=>{const rate=Number(f.goldRate)>0?Number(f.goldRate):rateForPurity(x?.purity);setLines(v=>[...v,emptyLine(x,rate)]);setItemSearch('');setItemOpen(false);setCalc(null);setLastCreated(null);};
 const removeItem=(id:string)=>{setLines(v=>v.filter(x=>x.id!==id));setCalc(null);};
 const updateLine=(id:string,k:keyof Line,v:any)=>setLines(vs=>vs.map(x=>x.id===id?{...x,[k]:v}:x));
 const scanBarcodeValue=async(value:string)=>{const clean=String(value||'').trim();if(!clean||scanBusy)return;setScanBusy(true);try{const r=await api.get(`/barcode/scan/${encodeURIComponent(clean)}`);if(String(r.data?.status||'').toUpperCase()!=='IN_STOCK'){onNotice(`Scanned item is ${r.data?.status||'not available'} and cannot be billed.`);return;}let x=items.find(i=>String(i.id)===String(r.data?.itemId));if(!x){const refreshed=await domainItems();setItems(refreshed.data);x=refreshed.data.find((i:any)=>String(i.id)===String(r.data?.itemId));}if(!x){onNotice('Barcode found, but the item is not available in this branch.');return;}if(lines.some(l=>String(l.jewelleryItemId)===String(x.id))){onNotice('This item is already added to the invoice.');return;}addItem(x);setBarcode('');onNotice(`Added ${r.data?.tagNo||clean} to invoice.`);window.setTimeout(()=>barcodeRef.current?.focus(),0);}catch(err:any){onNotice(err?.response?.data?.message||'Barcode/tag not found');}finally{setScanBusy(false);}};
 const scanBarcode=()=>scanBarcodeValue(barcode);
 const calculate=async()=>{if(!lines.length){onNotice('Add at least one jewellery item before calculating.');return;}const commonRate=Number(f.goldRate||0);if(commonRate<=0){onNotice('Gold rate is required.');return;}try{const r=await calculateMultiBilling({goldRate:commonRate,items:lines.map(x=>toPayloadLine(x,commonRate)),gstPercent:Number(f.gstPercent||0),discount:Number(f.discount||0)});setCalc(r.data);update('paymentAmount',Number(r.data?.total||0));setLines(v=>v.map(x=>({...x,goldRate:commonRate})));}catch(err:any){onNotice(err?.response?.data?.message||'Unable to calculate invoice total');}};
 const save=async(e:FormEvent)=>{e.preventDefault();if(!ready){onNotice('Select company and branch context first.');return;}if(!f.customerId){onNotice('Select a customer.');return;}if(!lines.length){onNotice('Add at least one jewellery item.');return;}if(Number(f.goldRate||0)<=0){onNotice('Gold rate is required.');return;}try{const payload={invoiceNo:f.invoiceNo,saleDate:f.saleDate,saleTime:f.saleTime,customerId:Number(f.customerId),goldRate:Number(f.goldRate||0),items:lines.map(x=>toPayloadLine(x,Number(f.goldRate||0))),gstPercent:Number(f.gstPercent||0),discount:Number(f.discount||0),paymentMode:f.paymentMode,paymentAmount:Number(f.paymentAmount||0)};const r=await createDomainBilling(payload);setLastCreated({id:Number(r.data.id),invoiceNo:r.data.invoiceNo,itemCount:r.data.itemCount});setCalc(null);onNotice(`Invoice ${r.data.invoiceNo} created with ${r.data.itemCount} item${r.data.itemCount===1?'':'s'} and stock movement.`);setLines([]);const resetDate=new Date();setF({invoiceNo:`INV-${Date.now()}`,saleDate:resetDate.toISOString().slice(0,10),saleTime:resetDate.toTimeString().slice(0,5),customerId:'',goldRate:Number(marketRates.find((x:any)=>String(x.karat??x.purity??'').replace(/[^0-9]/g,'')==='22')?.ratePerGram||0),gstPercent:3,discount:0,paymentMode:'CASH',paymentAmount:0});setItemSearch('');setItemOpen(false);setCustomerSearch('');setCustomerOpen(false);try{const r2=await domainItems();setItems(r2.data);}catch{onNotice(`Invoice ${r.data.invoiceNo} was created, but stock refresh failed. Please refresh Billing.`);}}catch(err:any){onNotice(err?.response?.data?.message||'Unable to create invoice');}};
 const openCreatedPdf=async()=>{if(!lastCreated?.id)return;const popup=window.open('about:blank','_blank');try{const response=await salePdf(Number(lastCreated.id));const url=URL.createObjectURL(new Blob([response.data],{type:'application/pdf'}));if(popup){popup.location.href=url;popup.focus();}else{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.download=`${lastCreated.invoiceNo||'invoice'}.pdf`;a.click();}window.setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(err:any){popup?.close();onNotice(err?.response?.data?.message||'Unable to open invoice PDF');}};
 const sendCreatedWhatsApp=async()=>{if(!lastCreated?.id)return;try{const response=await sendInvoiceWhatsApp(Number(lastCreated.id));onNotice(response?.data?.status==='SENT'?'Invoice sent on WhatsApp.':(response?.data?.message||'WhatsApp message submitted.'));}catch(err:any){onNotice(err?.response?.data?.message||'Unable to send invoice on WhatsApp');}};
 const money=(v:any)=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
 return <div className="billingLayout billingSimpleMode">
  <div className="panel billingMainPanel">
   <div className="panelHead billingTitleRow">
    <div><span className="eyebrow">BILLING COUNTER</span><h2>New Bill</h2><small className="billingSubtext">Add customer → add jewellery → confirm total.</small></div>
    <div className="billingModeTools"><span className={ready?'pill success':'pill'}>{ready?'READY':'SELECT CONTEXT'}</span></div>
   </div>
   {ready&&<form className="formGrid billingForm" onSubmit={save}>
    <div className="billingDocumentMeta">
      <label><span>Invoice number</span><input value={f.invoiceNo} onChange={e=>update('invoiceNo',e.target.value)} aria-label="Invoice number"/></label>
      <label><span>Invoice date</span><input type="date" value={f.saleDate} onChange={e=>update('saleDate',e.target.value)} aria-label="Invoice date"/></label>
      <label><span>Invoice time</span><input type="time" value={f.saleTime} onChange={e=>update('saleTime',e.target.value)} aria-label="Invoice time"/></label>
    </div>
    <div className="barcodeScannerCard billingScannerSimple">
      <div><span className="billingStep">1</span><div><b>Scan or search jewellery</b><small>Use barcode/tag or search by product.</small></div></div>
      <div className="barcodeScanRow"><div className="smartScanField billingSmartScanField"><input ref={barcodeRef} value={barcode} onChange={e=>setBarcode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();scanBarcode();}}} placeholder="Scan or enter barcode / tag no" aria-label="Scan or enter barcode or tag number"/><button type="button" className="fieldScanButton" aria-label="Scan barcode with camera" title={scanBusy?'Scanning…':'Scan barcode'} disabled={scanBusy} onClick={()=>setCameraOpen(true)}><span className="scanFieldIcon" aria-hidden="true">▦</span><span className="scanFieldText">Scan</span></button></div></div>
    </div>
    <div className="billingTwoColumn">
      <label className="fieldLabel customerBillingField"><span>Customer <em>required</em></span><div className="customerSelectRow"><div className="customerPicker" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setCustomerOpen(false)}}><input required={!f.customerId&&!newCustomerMode} aria-label="Search customer" role="combobox" aria-expanded={customerOpen} value={selectedCustomer?`${selectedCustomer.name} · ${selectedCustomer.phone||'no phone'}`:customerSearch} placeholder="Search customer name or phone" disabled={newCustomerMode} onFocus={()=>setCustomerOpen(true)} onChange={e=>{setCustomerSearch(e.target.value);setCustomerOpen(true);if(f.customerId)update('customerId','')}} onKeyDown={e=>{if(e.key==='Escape')setCustomerOpen(false);if(e.key==='Enter'&&filteredCustomers[0]){e.preventDefault();update('customerId',String(filteredCustomers[0].id));setCustomerSearch('');setCustomerOpen(false);}}}/>{customerOpen&&!newCustomerMode&&<div className="customerPickerMenu">{filteredCustomers.length?filteredCustomers.map(x=><button type="button" key={x.id} className="customerPickerOption" onMouseDown={e=>e.preventDefault()} onClick={()=>{update('customerId',String(x.id));setCustomerSearch('');setCustomerOpen(false)}}><strong>{x.name||'Unnamed customer'}</strong><span>{x.phone||'No phone'}{x.email?` · ${x.email}`:''}</span></button>):<div className="customerPickerEmpty">No customer matches this search.</div>}</div>}</div><button type="button" className="secondary customerAddButton" onClick={()=>{setNewCustomerMode(v=>!v);setCustomerOpen(false)}}>{newCustomerMode?'Use existing':'＋ New customer'}</button></div></label>
      <label className="fieldLabel commonGoldRateField"><span>Gold rate / gram <em>used for this bill</em></span><input autoFocus type="number" min="0" step="0.001" value={f.goldRate} onChange={e=>{const rate=Number(e.target.value);update('goldRate',rate);setLines(v=>v.map(x=>({...x,goldRate:rate})));setCalc(null);}} placeholder="Enter gold rate"/></label>
    </div>
    {newCustomerMode&&<div className="inlineCustomerCard"><div className="inlineCustomerGrid"><input required placeholder="Customer name *" value={newCustomer.name} onChange={e=>setNewCustomer({...newCustomer,name:e.target.value})}/><input required placeholder="Phone number *" inputMode="tel" value={newCustomer.phone} onChange={e=>setNewCustomer({...newCustomer,phone:e.target.value})}/><input placeholder="Email" value={newCustomer.email} onChange={e=>setNewCustomer({...newCustomer,email:e.target.value})}/><input placeholder="GSTIN" value={newCustomer.gstin} onChange={e=>setNewCustomer({...newCustomer,gstin:e.target.value})}/><input className="wide" placeholder="Address" value={newCustomer.address} onChange={e=>setNewCustomer({...newCustomer,address:e.target.value})}/></div><button type="button" className="primary saveCustomerButton" disabled={customerSaving} onClick={async()=>{if(!newCustomer.name.trim()||!newCustomer.phone.trim()){onNotice('Customer name and phone number are required.');return;}setCustomerSaving(true);try{const r=await createDomainCustomer({...newCustomer,name:newCustomer.name.trim(),phone:newCustomer.phone.trim()});const saved=r.data||{};setCustomers(v=>[saved,...v.filter(x=>String(x.id)!==String(saved.id))]);update('customerId',String(saved.id));setNewCustomerMode(false);setNewCustomer({name:'',phone:'',email:'',gstin:'',address:''});onNotice(`Customer ${saved.name||'record'} saved and selected.`);}catch(err:any){onNotice(err?.response?.data?.message||'Unable to save customer');}finally{setCustomerSaving(false);}}}>{customerSaving?'Saving customer…':'Save customer & use for bill'}</button></div>}
    <div className="fieldLabel itemPickerField customerBillingField"><span>2. Add jewellery item <em>required</em></span><div className="itemPicker" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setItemOpen(false)}}><input aria-label="Search jewellery item" role="combobox" aria-expanded={itemOpen} value={itemSearch} placeholder="Search product, tag, barcode or HUID" onFocus={()=>setItemOpen(true)} onChange={e=>{setItemSearch(e.target.value);setItemOpen(true)}} onKeyDown={e=>{if(e.key==='Escape')setItemOpen(false);if(e.key==='Enter'&&filteredItems[0]){e.preventDefault();addItem(filteredItems[0]);}}}/>{itemOpen&&<div className="itemPickerMenu">{filteredItems.length?filteredItems.map(x=><button type="button" key={x.id} className="itemPickerOption" onMouseDown={e=>e.preventDefault()} onClick={()=>addItem(x)}><strong>{x?.product?.name||'Unnamed product'}</strong><span>Tag: {x?.tag?.tagNo||'—'} · Barcode: {x?.tag?.barcode||'—'}</span><small>{x?.purity?.karat||x?.purity?.name||'—'} · Net {x?.netWeight??0} g</small></button>):<div className="itemPickerEmpty">No available item matches this search.</div>}</div>}</div><small className="fieldHint">Select an item to add it to this bill.</small></div>
    <div className="multiItemCard simpleCart"><div className="multiItemHead"><div><span className="eyebrow">BILL ITEMS</span><strong>{lines.length} item{lines.length===1?'':'s'}</strong></div><small>All weights and charges are visible and editable.</small></div>{lines.length===0?<div className="emptyCart">No jewellery added yet.</div>:<div className="invoiceItemsList">{lines.map((x,i)=><div className="invoiceItemRow" key={x.id}><div className="invoiceItemInfo"><b>{i+1}. {x.name}</b><span>{x.purity}{x.tag?` · Tag ${x.tag}`:''}</span><small>Net {Number(x.netWeight||0).toFixed(3)} g</small></div><div className="simpleItemCore"><label>Gross<input type="number" step="0.001" value={x.grossWeight} onChange={e=>updateLine(x.id,'grossWeight',Number(e.target.value))}/></label><label>Net<input type="number" step="0.001" value={x.netWeight} onChange={e=>updateLine(x.id,'netWeight',Number(e.target.value))}/></label></div><div className="simpleItemActions"><button type="button" className="removeItemButton" onClick={()=>removeItem(x.id)}>Remove</button></div><div className="invoiceItemFields simpleAdvancedFields alwaysVisibleFields"><label>Stone weight<input type="number" step="0.001" value={x.stoneWeight} onChange={e=>{const stone=Number(e.target.value);updateLine(x.id,'stoneWeight',stone);updateLine(x.id,'netWeight',Math.max(x.grossWeight-stone,0));}}/></label><label>Wastage %<input type="number" step="0.001" value={x.wastagePercent} onChange={e=>updateLine(x.id,'wastagePercent',Number(e.target.value))}/></label><label>Making ₹<input type="number" step="0.001" value={x.makingCharge} onChange={e=>updateLine(x.id,'makingCharge',Number(e.target.value))}/></label><label>Stone ₹<input type="number" step="0.001" value={x.stoneCharge} onChange={e=>updateLine(x.id,'stoneCharge',Number(e.target.value))}/></label><label>Other ₹<input type="number" step="0.001" value={x.otherCharge} onChange={e=>updateLine(x.id,'otherCharge',Number(e.target.value))}/></label></div></div>)}</div>}</div>
    <div className="billingOptional alwaysVisiblePayment"><div className="billingOptionalTitle"><span>Payment & adjustments</span><small>Complete these before creating the bill.</small></div><div className="billingOptionalGrid"><label className="fieldLabel"><span>GST (%)</span><input value={f.gstPercent} type="number" step="0.001" onChange={e=>update('gstPercent',e.target.value)}/></label><label className="fieldLabel"><span>Discount (₹)</span><input value={f.discount} type="number" step="0.001" onChange={e=>update('discount',e.target.value)}/></label><label className="fieldLabel"><span>Payment received (₹)</span><input value={f.paymentAmount} type="number" step="0.001" onChange={e=>update('paymentAmount',e.target.value)}/></label><label className="fieldLabel"><span>Payment mode</span><select value={f.paymentMode} onChange={e=>update('paymentMode',e.target.value)}><option>CASH</option><option>UPI</option><option>CARD</option><option>CREDIT</option></select></label></div></div>
    <div className="buttonRow billingActions"><button type="button" className="secondary calculateButton" onClick={calculate}>Calculate total</button><button type="submit" className="primary createInvoiceButton">Create bill{lines.length?` · ${lines.length} item${lines.length===1?'':'s'}`:''}</button></div>
   </form>}
   <BarcodeCameraScanner open={cameraOpen} onClose={()=>setCameraOpen(false)} onDetected={v=>{setCameraOpen(false);scanBarcodeValue(v)}}/>
  </div>
  <div className="invoicePreview ultraGlassGrid">{lastCreated?<div className="invoiceCreatedCard"><span className="eyebrow">INVOICE CREATED</span><h2>{lastCreated.invoiceNo}</h2><p>{lastCreated.itemCount} jewellery item{lastCreated.itemCount===1?'':'s'} billed. Stock has been reduced and the sale is saved successfully.</p><div className="invoiceActionRow"><button type="button" className="primary" onClick={openCreatedPdf}>Print invoice</button><button type="button" className="secondary" onClick={sendCreatedWhatsApp}>Send WhatsApp</button><button type="button" className="ghost" onClick={()=>setLastCreated(null)}>New bill</button></div></div>:<><span className="eyebrow">BILL SUMMARY</span><h2>{f.invoiceNo}</h2><div className="calcRows">{[['Items',calc?.itemCount??lines.length],['Gold value',calc?.goldValue],['Wastage',calc?.wastageValue],['Subtotal',calc?.subtotal],['GST',calc?.gst],['Discount',calc?.discount??f.discount]].map(([a,b])=><div key={String(a)}><span>{a}</span><b>{a==='Items'?String(b||0):money(b)}</b></div>)}</div><div className="totalLine"><span>Total payable</span><strong>{money(calc?.total)}</strong></div><p className="muted">Add multiple ornaments, set the common gold rate, verify weights and charges, then calculate. Payment received is auto-filled to the total and remains editable.</p></>}</div>
 </div>;
}

function toPayloadLine(x:Line, commonRate?:number){return {jewelleryItemId:Number(x.jewelleryItemId),grossWeight:Number(x.grossWeight||0),stoneWeight:Number(x.stoneWeight||0),netWeight:Number(x.netWeight||0),goldRate:Number(commonRate??x.goldRate??0),wastagePercent:Number(x.wastagePercent||0),makingCharge:Number(x.makingCharge||0),stoneCharge:Number(x.stoneCharge||0),otherCharge:Number(x.otherCharge||0)};}
