import {FormEvent, useEffect, useMemo, useRef, useState} from 'react';
import {
  api, login, registerCompany, adminReset, otpRequest, otpVerify, me, users, createUser, enableUser,
  approvals, approve, reject, companies, createCompany, branches, createBranch, records, createRecord,
  updateRecord, deleteRecord, dashboard, report, audit, calculateBilling, createBilling, createDomainBilling, invoicePdf,
  domainCustomers, createDomainCustomer, domainCategories, createDomainCategory, domainDesigns, createDomainDesign,
  domainProducts, createDomainProduct, domainTags, createDomainTag, domainItems, createDomainItem, domainPurities,
  domainGoldRates, createDomainGoldRate, headerGoldRates, domainStock, domainStockMovements, createDomainTransfer, createDomainStockMovement, domainSuppliers, domainPurchases, domainOldGold, domainRepairs, domainCustomOrders, domainPayments, domainAdvances, phase3Transfer, phase3CompleteTransfer, phase3Purchase, phase3OldGold, phase3RepairUpdate, phase3CustomOrderUpdate, phase3Advance, phase3Outstanding, phase3Report
} from '../api';
import {Role,User,ThemeKey,RecordItem,Company,Branch} from '../shared/types';
import {Table,Empty,Field} from '../shared/ui';
import './Billing.css';
import BarcodeCameraScanner from './BarcodeCameraScanner';
export default function BillingModule({ready,onNotice}:{ready:boolean;onNotice:(x:string)=>void}){
 const [customers,setCustomers]=useState<any[]>([]),[items,setItems]=useState<any[]>([]);
 const [f,setF]=useState<any>({invoiceNo:`INV-${Date.now()}`,saleDate:new Date().toISOString().slice(0,10),grossWeight:0,stoneWeight:0,netWeight:0,goldRate:0,wastagePercent:0,makingCharge:0,stoneCharge:0,otherCharge:0,gstPercent:3,paymentMode:'CASH',paymentAmount:0});
 const [calc,setCalc]=useState<any>(null);
 const [barcode,setBarcode]=useState('');
 const [scanBusy,setScanBusy]=useState(false);
 const [cameraOpen,setCameraOpen]=useState(false);
 const [marketRates,setMarketRates]=useState<any[]>([]);
 const barcodeRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!ready){setCustomers([]);setItems([]);setMarketRates([]);return;}Promise.all([domainCustomers(),domainItems(),headerGoldRates()]).then(([c,i,m])=>{setCustomers(c.data);setItems(i.data);setMarketRates(Array.isArray(m.data?.marketRates)?m.data.marketRates:[]);}).catch(e=>onNotice(e?.response?.data?.message||'Unable to load billing masters'));},[ready]);
 useEffect(()=>{if(ready){window.setTimeout(()=>barcodeRef.current?.focus(),150);}},[ready]);
 const selectedItem=items.find(x=>String(x.id)===String(f.jewelleryItemId));
 const rateForPurity=(purity:any)=>{const key=String(purity?.karat||purity?.name||'').toUpperCase();return marketRates.find(x=>String(x.karat||'').toUpperCase()===key)?.ratePerGram||0;};
 const selectItem=(id:string)=>{const x=items.find(i=>String(i.id)===String(id));if(!x)return;setF((v:any)=>({...v,jewelleryItemId:String(id),grossWeight:x?.grossWeight||0,stoneWeight:x?.stoneWeight||0,netWeight:x?.netWeight||0,purity:x?.purity?.name||'',goldRate:Number(v.goldRate||0)||Number(rateForPurity(x?.purity)||0)}));};
 const onCameraDetected=(value:string)=>{setCameraOpen(false);setBarcode(value);window.setTimeout(()=>scanBarcodeValue(value),0);};
 const scanBarcodeValue=async(value:string)=>{const clean=String(value||'').trim();if(!clean||scanBusy)return;setScanBusy(true);try{let r=await api.get(`/barcode/scan/${encodeURIComponent(clean)}`);if(String(r.data?.status||'').toUpperCase()!=='IN_STOCK'){onNotice(`Scanned item is ${r.data?.status||'not available'} and cannot be billed.`);return;}let id=String(r.data?.itemId||'');let x=items.find(i=>String(i.id)===id);if(!x){const refreshed=await domainItems();setItems(refreshed.data);x=refreshed.data.find((i:any)=>String(i.id)===id);}if(!x){onNotice('Barcode found, but the jewellery item is not available in the current branch.');return;}selectItem(id);setBarcode('');onNotice(`Scanned ${r.data?.barcode||clean} · ${r.data?.tagNo||''}`);window.setTimeout(()=>barcodeRef.current?.focus(),0);}catch(err:any){onNotice(err?.response?.data?.message||'Barcode/tag not found');}finally{setScanBusy(false);}};
 const scanBarcode=async()=>scanBarcodeValue(barcode);
 const calculate=async()=>{try{const r=await calculateBilling({grossWeight:Number(f.grossWeight||0),stoneWeight:Number(f.stoneWeight||0),netWeight:Number(f.netWeight||0),goldRate:Number(f.goldRate||0),wastagePercent:Number(f.wastagePercent||0),makingCharge:Number(f.makingCharge||0),stoneCharge:Number(f.stoneCharge||0),otherCharges:Number(f.otherCharge||0),gstPercent:Number(f.gstPercent||0)});setCalc(r.data);}catch(err:any){onNotice(err?.response?.data?.message||'Unable to calculate');}};
 const save=async(e:FormEvent)=>{e.preventDefault();if(!ready){onNotice('Select company and branch context first.');return;}try{const r=await createDomainBilling({...f,customerId:Number(f.customerId),jewelleryItemId:Number(f.jewelleryItemId),grossWeight:Number(f.grossWeight||0),stoneWeight:Number(f.stoneWeight||0),netWeight:Number(f.netWeight||0),goldRate:Number(f.goldRate||0),wastagePercent:Number(f.wastagePercent||0),makingCharge:Number(f.makingCharge||0),stoneCharge:Number(f.stoneCharge||0),otherCharge:Number(f.otherCharge||0),gstPercent:Number(f.gstPercent||0),discount:Number(f.discount||0),paymentAmount:Number(f.paymentAmount||0)});setCalc(r.data);onNotice(`Invoice ${r.data.invoiceNo} created with stock movement.`);setF({...f,invoiceNo:`INV-${Date.now()}`,customerId:'',jewelleryItemId:'',paymentAmount:0});const r2=await domainItems();setItems(r2.data);}catch(err:any){onNotice(err?.response?.data?.message||'Unable to create invoice');}};
 return <div className="billingLayout"><div className="panel"><div className="panelHead"><div><span className="eyebrow">NORMALIZED JEWELLERY BILLING</span><h2>New Bill</h2></div><span className={ready?'pill success':'pill'}>{ready?'READY':'SELECT CONTEXT'}</span></div>{ready&&<form className="formGrid billingForm" onSubmit={save}>
  <div className="barcodeScannerCard"><div><span className="eyebrow">BARCODE SCANNER</span><b>Scan jewellery tag</b><small>Use a USB/Bluetooth scanner, or type the barcode/tag number and press Enter.</small></div><div className="barcodeScanRow"><input ref={barcodeRef} value={barcode} autoComplete="off" inputMode="numeric" placeholder="Scan barcode / tag no" onChange={e=>setBarcode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();scanBarcode();}}}/><button type="button" className="secondary" disabled={scanBusy||!barcode.trim()} onClick={scanBarcode}>{scanBusy?'Scanning…':'Scan'}</button><button type="button" className="cameraButton" disabled={scanBusy} onClick={()=>setCameraOpen(true)}>📷 Camera</button></div></div>
  <input value={f.invoiceNo} placeholder="Invoice number" onChange={e=>setF({...f,invoiceNo:e.target.value})}/><select required value={f.customerId||''} onChange={e=>setF({...f,customerId:e.target.value})}><option value="">Customer</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name} · {x.phone||'no phone'}</option>)}</select>
  <select required value={f.jewelleryItemId||''} onChange={e=>selectItem(e.target.value)}><option value="">Available tagged jewellery item</option>{items.filter(x=>x.status==='IN_STOCK').map(x=><option key={x.id} value={x.id}>{x.tag?.tagNo} · {x.product?.name} · {x.netWeight}g</option>)}</select><input value={f.purity||selectedItem?.purity?.name||''} readOnly placeholder="Purity"/>
  <input value={f.grossWeight} type="number" step="0.001" placeholder="Gross weight g" required onChange={e=>setF({...f,grossWeight:e.target.value})}/><input value={f.stoneWeight} type="number" step="0.001" placeholder="Stone weight g" onChange={e=>setF({...f,stoneWeight:e.target.value,netWeight:Number(f.grossWeight||0)-Number(e.target.value||0)})}/>
  <input value={f.netWeight} type="number" step="0.001" placeholder="Net weight g" required onChange={e=>setF({...f,netWeight:e.target.value})}/><input value={f.goldRate} type="number" step="0.001" placeholder="Gold rate / g" required onChange={e=>setF({...f,goldRate:e.target.value})}/>
  <input value={f.wastagePercent} type="number" step="0.001" placeholder="Wastage %" onChange={e=>setF({...f,wastagePercent:e.target.value})}/><input value={f.makingCharge} type="number" step="0.001" placeholder="Making charge" onChange={e=>setF({...f,makingCharge:e.target.value})}/>
  <input value={f.stoneCharge} type="number" step="0.001" placeholder="Stone charge" onChange={e=>setF({...f,stoneCharge:e.target.value})}/><input value={f.otherCharge||''} type="number" step="0.001" placeholder="Other charge" onChange={e=>setF({...f,otherCharge:e.target.value})}/>
  <input value={f.gstPercent} type="number" step="0.001" placeholder="GST %" onChange={e=>setF({...f,gstPercent:e.target.value})}/><input value={f.paymentAmount} type="number" step="0.001" placeholder="Payment received" onChange={e=>setF({...f,paymentAmount:e.target.value})}/>
  <select value={f.paymentMode} onChange={e=>setF({...f,paymentMode:e.target.value})}><option>CASH</option><option>UPI</option><option>CARD</option><option>CREDIT</option></select>
  <div className="buttonRow"><button type="button" className="secondary" onClick={calculate}>Calculate</button><button className="primary">Create invoice & reduce stock</button></div>
 </form>}<BarcodeCameraScanner open={cameraOpen} onClose={()=>setCameraOpen(false)} onDetected={onCameraDetected}/></div><div className="invoicePreview"><span className="eyebrow">IMMUTABLE SALE CALCULATION</span><h2>{f.invoiceNo}</h2><div className="calcRows">{[['Gold value',calc?.goldValue],['Wastage',calc?.wastageValue],['Making',f.makingCharge],['Stone',f.stoneCharge],['GST',calc?.gst]].map(([a,b])=><div key={String(a)}><span>{a}</span><b>₹{Number(b||0).toLocaleString('en-IN')}</b></div>)}</div><div className="totalLine"><span>Total</span><strong>₹{Number(calc?.total||0).toLocaleString('en-IN')}</strong></div><p className="muted">The normalized sale stores the applied gold rate, sale item, calculation values and payment status. Stock is marked SOLD transactionally.</p></div></div>
}

