import {FormEvent, useEffect, useMemo, useState} from 'react';
import {
  api, login, registerCompany, adminReset, otpRequest, otpVerify, me, users, createUser, enableUser,
  approvals, approve, reject, companies, createCompany, branches, createBranch, records, createRecord,
  updateRecord, deleteRecord, dashboard, report, audit, calculateBilling, createBilling, createDomainBilling, invoicePdf,
  domainCustomers, createDomainCustomer, domainCategories, createDomainCategory, domainDesigns, createDomainDesign,
  domainProducts, createDomainProduct, domainTags, createDomainTag, domainItems, createDomainItem, domainPurities,
  domainGoldRates, createDomainGoldRate, domainStock, domainStockMovements, createDomainTransfer, createDomainStockMovement, domainSuppliers, domainPurchases, domainOldGold, domainRepairs, domainCustomOrders, domainPayments, domainAdvances, phase3Transfer, phase3CompleteTransfer, phase3Purchase, phase3OldGold, phase3RepairUpdate, phase3CustomOrderUpdate, phase3Advance, phase3Outstanding, phase3Report
} from '../api';
import {Role,User,ThemeKey,RecordItem,Company,Branch} from '../shared/types';
import {Table,Empty,Field} from '../shared/ui';
import './Jewellery.css';
export default function JewelleryModule({ready,onNotice}:{ready:boolean;onNotice:(x:string)=>void}){
 const [tab,setTab]=useState<'CATEGORIES'|'DESIGNS'|'PRODUCTS'|'TAGS'|'ITEMS'>('ITEMS');
 const [categories,setCategories]=useState<any[]>([]),[designs,setDesigns]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[tags,setTags]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[purities,setPurities]=useState<any[]>([]);
 const [f,setF]=useState<any>({});
 const load=()=>{if(!ready)return;Promise.all([domainCategories(),domainDesigns(),domainProducts(),domainTags(),domainItems(),domainPurities()]).then(([a,b,c,d,e,p])=>{setCategories(a.data);setDesigns(b.data);setProducts(c.data);setTags(d.data);setItems(e.data);setPurities(p.data);}).catch(e=>onNotice(e?.response?.data?.message||'Unable to load jewellery master data'));};
 useEffect(load,[ready]);
 const save=async(e:FormEvent)=>{e.preventDefault();if(!ready){onNotice('Select company and branch context first.');return;}try{
   if(tab==='CATEGORIES') await createDomainCategory({name:f.name,code:f.code});
   if(tab==='DESIGNS') await createDomainDesign({name:f.name,code:f.code,description:f.description,categoryId:Number(f.categoryId)});
   if(tab==='PRODUCTS') await createDomainProduct({name:f.name,sku:f.sku,description:f.description,categoryId:Number(f.categoryId),designId:f.designId?Number(f.designId):undefined});
   if(tab==='TAGS') await createDomainTag({tagNo:f.tagNo,barcode:f.barcode,status:f.status||'AVAILABLE'});
   if(tab==='ITEMS') await createDomainItem({productId:Number(f.productId),tagId:Number(f.tagId),purityId:Number(f.purityId),grossWeight:Number(f.grossWeight||0),stoneWeight:Number(f.stoneWeight||0),netWeight:Number(f.netWeight||Number(f.grossWeight||0)-Number(f.stoneWeight||0)),huid:f.huid,wastagePercent:Number(f.wastagePercent||0),makingCharge:Number(f.makingCharge||0),stoneValue:Number(f.stoneValue||0),status:'IN_STOCK'});
   setF({});await load();onNotice(`${tab.toLowerCase()} created in PostgreSQL.`);
 }catch(e:any){onNotice(e?.response?.data?.message||`Unable to create ${tab.toLowerCase()}`);}};
 const rows=tab==='CATEGORIES'?categories:tab==='DESIGNS'?designs:tab==='PRODUCTS'?products:tab==='TAGS'?tags:items;
 return <div><div className="reportTabs">{(['CATEGORIES','DESIGNS','PRODUCTS','TAGS','ITEMS'] as const).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>{setTab(x);setF({});}}>{x}</button>)}</div><div className="moduleGrid"><div className="panel"><span className="eyebrow">JEWELLERY MASTER</span><h2>Create {tab.toLowerCase()}</h2><form className="formGrid" onSubmit={save}>
 {tab==='CATEGORIES'&&<><input required placeholder="Category name" value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="Category code" value={f.code||''} onChange={e=>setF({...f,code:e.target.value})}/></>}
 {tab==='DESIGNS'&&<><input required placeholder="Design name" value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="Design code" value={f.code||''} onChange={e=>setF({...f,code:e.target.value})}/><select required value={f.categoryId||''} onChange={e=>setF({...f,categoryId:e.target.value})}><option value="">Category</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><textarea placeholder="Description" value={f.description||''} onChange={e=>setF({...f,description:e.target.value})}/></>}
 {tab==='PRODUCTS'&&<><input required placeholder="Product name" value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="SKU" value={f.sku||''} onChange={e=>setF({...f,sku:e.target.value})}/><select required value={f.categoryId||''} onChange={e=>setF({...f,categoryId:e.target.value})}><option value="">Category</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={f.designId||''} onChange={e=>setF({...f,designId:e.target.value})}><option value="">Design (optional)</option>{designs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><textarea placeholder="Description" value={f.description||''} onChange={e=>setF({...f,description:e.target.value})}/></>}
 {tab==='TAGS'&&<><input required placeholder="Tag number" value={f.tagNo||''} onChange={e=>setF({...f,tagNo:e.target.value})}/><input required placeholder="Barcode" value={f.barcode||''} onChange={e=>setF({...f,barcode:e.target.value})}/><select value={f.status||'AVAILABLE'} onChange={e=>setF({...f,status:e.target.value})}><option>AVAILABLE</option><option>HOLD</option></select></>}
 {tab==='ITEMS'&&<><select required value={f.productId||''} onChange={e=>setF({...f,productId:e.target.value})}><option value="">Product</option>{products.map(x=><option key={x.id} value={x.id}>{x.name} · {x.sku}</option>)}</select><select required value={f.tagId||''} onChange={e=>setF({...f,tagId:e.target.value})}><option value="">Tag</option>{tags.map(x=><option key={x.id} value={x.id}>{x.tagNo} · {x.barcode}</option>)}</select><select required value={f.purityId||''} onChange={e=>setF({...f,purityId:e.target.value})}><option value="">Purity</option>{purities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required type="number" step="0.001" placeholder="Gross weight (g)" value={f.grossWeight||''} onChange={e=>setF({...f,grossWeight:e.target.value})}/><input type="number" step="0.001" placeholder="Stone weight (g)" value={f.stoneWeight||''} onChange={e=>setF({...f,stoneWeight:e.target.value})}/><input type="number" step="0.001" placeholder="Net weight (g)" value={f.netWeight||''} onChange={e=>setF({...f,netWeight:e.target.value})}/><input placeholder="HUID" value={f.huid||''} onChange={e=>setF({...f,huid:e.target.value})}/><input type="number" step="0.001" placeholder="Wastage %" value={f.wastagePercent||''} onChange={e=>setF({...f,wastagePercent:e.target.value})}/><input type="number" step="0.001" placeholder="Making charge" value={f.makingCharge||''} onChange={e=>setF({...f,makingCharge:e.target.value})}/></>}
 <button className="primary">Create {tab.toLowerCase()}</button></form></div><div className="panel"><div className="panelHead"><h2>{rows.length} {tab.toLowerCase()}</h2><button className="ghost" onClick={load}>Refresh</button></div><Table><thead><tr>{tab==='CATEGORIES'?<><th>Name</th><th>Code</th></>:tab==='DESIGNS'?<><th>Name</th><th>Code</th><th>Category</th></>:tab==='PRODUCTS'?<><th>Name</th><th>SKU</th><th>Category</th></>:tab==='TAGS'?<><th>Tag</th><th>Barcode</th><th>Status</th></>:<><th>Product</th><th>Tag</th><th>Purity</th><th>Net weight</th><th>Status</th></>}</tr></thead><tbody>{rows.map(x=><tr key={x.id}>{tab==='CATEGORIES'?<><td>{x.name}</td><td>{x.code}</td></>:tab==='DESIGNS'?<><td>{x.name}</td><td>{x.code}</td><td>{x.category?.name||'—'}</td></>:tab==='PRODUCTS'?<><td>{x.name}</td><td>{x.sku}</td><td>{x.category?.name||'—'}</td></>:tab==='TAGS'?<><td>{x.tagNo}</td><td>{x.barcode}</td><td>{x.status}</td></>:<><td>{x.product?.name||'—'}</td><td>{x.tag?.tagNo||'—'}</td><td>{x.purity?.name||'—'}</td><td>{x.netWeight}</td><td><span className="pill success">{x.status}</span></td></>}</tr>)}</tbody></Table>{!rows.length&&<Empty text={`No ${tab.toLowerCase()} yet.`}/>}</div></div></div>
}

