import {FormEvent, useEffect, useMemo, useState} from 'react';
import {
  api, login, registerCompany, adminReset, otpRequest, otpVerify, me, users, createUser, enableUser,
  approvals, approve, reject, companies, createCompany, branches, createBranch, records, createRecord,
  updateRecord, deleteRecord, dashboard, report, audit, calculateBilling, createBilling, createDomainBilling, invoicePdf,
  domainCustomers, createDomainCustomer, domainCategories, createDomainCategory, domainDesigns, createDomainDesign,
  domainProducts, createDomainProduct, domainTags, createDomainTag, domainItems, createDomainItem, domainPurities,
  domainGoldRates, createDomainGoldRate, domainStock, domainStockMovements, createDomainTransfer, createDomainStockMovement, domainSuppliers, domainPurchases, domainOldGold, domainRepairs, domainCustomOrders, domainPayments, domainAdvances, phase3Transfer, phase3CompleteTransfer, phase3Purchase, phase3OldGold, phase3RepairUpdate, phase3CustomOrderUpdate, phase3Advance, phase3Outstanding, phase3Report
} from '../api';
import {Role,User,ThemeKey,RecordItem,Company,Branch} from '../shared/types';
import {Table,Empty,Field} from '../shared/ui';
import FormDrawer from '../shared/FormDrawer';
export function Phase3OperationsModule({module,ready,onNotice}:{module:string;ready:boolean;onNotice:(x:string)=>void}){
 const [list,setList]=useState<any[]>([]); const [customers,setCustomers]=useState<any[]>([]); const [items,setItems]=useState<any[]>([]); const [suppliers,setSuppliers]=useState<any[]>([]); const [branchesList,setBranchesList]=useState<any[]>([]); const [f,setF]=useState<any>({});
 const load=async()=>{if(!ready){setList([]);return;}try{
   if(module==='Inventory'){const [s,b]=await Promise.all([domainStock(),branches()]);setList(s.data);setBranchesList(b.data);}
   if(module==='Purchases'){const [p,s]=await Promise.all([domainPurchases(),domainSuppliers()]);setList(p.data);setSuppliers(s.data);setItems((await domainItems()).data);}
   if(module==='Old Gold'){const [o,c]=await Promise.all([domainOldGold(),domainCustomers()]);setList(o.data);setCustomers(c.data);}
   if(module==='Services'){const [r,c]=await Promise.all([domainRepairs(),domainCustomOrders()]);setList([...r.data.map((x:any)=>({...x,_kind:'REPAIR'})),...c.data.map((x:any)=>({...x,_kind:'CUSTOM_ORDER'}))]);setCustomers((await domainCustomers()).data);}
   if(module==='Payments'){const [p,a,c]=await Promise.all([domainPayments(),domainAdvances(),domainCustomers()]);setList([...p.data.map((x:any)=>({...x,_kind:'PAYMENT'})),...a.data.map((x:any)=>({...x,_kind:'ADVANCE'}))]);setCustomers(c.data);}
 }catch(e:any){onNotice(e?.response?.data?.message||`Unable to load ${module}`);}};
 useEffect(()=>{load();},[ready,module]);
 const save=async(e:FormEvent)=>{e.preventDefault();if(!ready){onNotice('Select company and branch context first.');return;}try{
   if(module==='Inventory'){const r=await phase3Transfer({fromBranchId:Number(f.fromBranchId),toBranchId:Number(f.toBranchId),items:[{jewelleryItemId:Number(f.jewelleryItemId)}],notes:f.notes});await phase3CompleteTransfer(r.data.id);onNotice(`Transfer ${r.data.transferNo} completed.`);}
   if(module==='Purchases'){await phase3Purchase({supplierId:Number(f.supplierId),purchaseNo:f.purchaseNo,items:[{description:f.description||'Jewellery',jewelleryItemId:Number(f.jewelleryItemId),grossWeight:Number(f.grossWeight||0),netWeight:Number(f.netWeight||0),rate:Number(f.rate||0),amount:Number(f.amount||0)}],gst:Number(f.gst||0)});onNotice('Purchase received and stock updated.');}
   if(module==='Old Gold'){await phase3OldGold({customerId:Number(f.customerId),transactionNo:f.transactionNo,transactionType:f.transactionType||'PURCHASE',items:[{description:f.description||'Old gold',grossWeight:Number(f.grossWeight||0),stoneWeight:Number(f.stoneWeight||0),netWeight:Number(f.netWeight||0),purity:f.purity||'22K',rate:Number(f.rate||0),amount:Number(f.amount||0)}],paymentAmount:Number(f.paymentAmount||0),paymentMode:f.paymentMode||'CASH'});onNotice('Old-gold transaction recorded.');}
   if(module==='Payments'){await phase3Advance({customerId:Number(f.customerId),advanceNo:f.advanceNo,amount:Number(f.amount||0),notes:f.notes});onNotice('Customer advance recorded.');}
   setF({});await load();
 }catch(e:any){onNotice(e?.response?.data?.message||`Unable to save ${module}`);}};
 const updateStatus=async(x:any)=>{try{if(x._kind==='REPAIR')await phase3RepairUpdate(x.id,{status:f[`status_${x.id}`]||x.status});else await phase3CustomOrderUpdate(x.id,{status:f[`status_${x.id}`]||x.status});await load();onNotice('Service status updated.');}catch(e:any){onNotice(e?.response?.data?.message||'Unable to update service');}};
 return <div className="moduleGrid hasDrawer"><FormDrawer needsManage={module==='Inventory'||module==='Purchases'} label="New entry" title="Create entry"><div className="panel"><div className="panelHead"><div><span className="eyebrow">PHASE 3 · NORMALIZED WORKFLOW</span><h2>{module}</h2></div><span className={ready?'pill success':'pill'}>{ready?'LIVE TRANSACTION':'CONTEXT REQUIRED'}</span></div>{ready&&<form className="formGrid" onSubmit={save}>
   {module==='Inventory'&&<><select required value={f.fromBranchId||''} onChange={e=>setF({...f,fromBranchId:e.target.value})}><option value="">From branch</option>{branchesList.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select required value={f.toBranchId||''} onChange={e=>setF({...f,toBranchId:e.target.value})}><option value="">To branch</option>{branchesList.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input required placeholder="Jewellery item ID" value={f.jewelleryItemId||''} onChange={e=>setF({...f,jewelleryItemId:e.target.value})}/><input placeholder="Notes" value={f.notes||''} onChange={e=>setF({...f,notes:e.target.value})}/></>}
   {module==='Purchases'&&<><select required value={f.supplierId||''} onChange={e=>setF({...f,supplierId:e.target.value})}><option value="">Supplier</option>{suppliers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required placeholder="Purchase number" value={f.purchaseNo||''} onChange={e=>setF({...f,purchaseNo:e.target.value})}/><select required value={f.jewelleryItemId||''} onChange={e=>setF({...f,jewelleryItemId:e.target.value})}><option value="">Tagged jewellery item</option>{items.map((x:any)=><option key={x.id} value={x.id}>{x.tag?.tagNo} · {x.product?.name}</option>)}</select><input placeholder="Description" value={f.description||''} onChange={e=>setF({...f,description:e.target.value})}/><input type="number" step="0.001" placeholder="Rate" value={f.rate||''} onChange={e=>setF({...f,rate:e.target.value})}/><input type="number" step="0.001" placeholder="Amount" required value={f.amount||''} onChange={e=>setF({...f,amount:e.target.value})}/></>}
   {module==='Old Gold'&&<><select required value={f.customerId||''} onChange={e=>setF({...f,customerId:e.target.value})}><option value="">Customer</option>{customers.map((x:any)=><option key={x.id} value={x.id}>{x.name} · {x.phone||''}</option>)}</select><select value={f.transactionType||'PURCHASE'} onChange={e=>setF({...f,transactionType:e.target.value})}><option>PURCHASE</option><option>EXCHANGE</option></select><input placeholder="Transaction number" value={f.transactionNo||''} onChange={e=>setF({...f,transactionNo:e.target.value})}/><input placeholder="Purity" value={f.purity||'22K'} onChange={e=>setF({...f,purity:e.target.value})}/><input type="number" step="0.001" placeholder="Net weight" value={f.netWeight||''} onChange={e=>setF({...f,netWeight:e.target.value})}/><input type="number" step="0.001" placeholder="Rate" value={f.rate||''} onChange={e=>setF({...f,rate:e.target.value})}/><input type="number" step="0.001" placeholder="Amount" required value={f.amount||''} onChange={e=>setF({...f,amount:e.target.value})}/><input type="number" step="0.001" placeholder="Payment amount" value={f.paymentAmount||''} onChange={e=>setF({...f,paymentAmount:e.target.value})}/></>}
   {module==='Payments'&&<><select required value={f.customerId||''} onChange={e=>setF({...f,customerId:e.target.value})}><option value="">Customer</option>{customers.map((x:any)=><option key={x.id} value={x.id}>{x.name} · {x.phone||''}</option>)}</select><input required type="number" step="0.001" placeholder="Advance amount" value={f.amount||''} onChange={e=>setF({...f,amount:e.target.value})}/><input placeholder="Advance number" value={f.advanceNo||''} onChange={e=>setF({...f,advanceNo:e.target.value})}/><input placeholder="Notes" value={f.notes||''} onChange={e=>setF({...f,notes:e.target.value})}/></>}
   {module!=='Services'&&<button className="primary">Execute {module} workflow</button>}
 </form>}
 {module==='Services'&&<p className="muted">Use the service records below to move repairs and custom orders through their lifecycle. Status changes are persisted to PostgreSQL and audited.</p>}
 </div></FormDrawer><div className="panel"><div className="panelHead"><div><span className="eyebrow">POSTGRESQL</span><h2>{list.length} records</h2></div><button className="ghost" onClick={load}>Refresh</button></div><Table><thead><tr><th>Type</th><th>Reference</th><th>Status</th><th>Amount</th><th>Action</th></tr></thead><tbody>{list.map((x:any)=><tr key={`${x._kind||module}-${x.id}`}><td>{x._kind||module}</td><td>{x.invoiceNo||x.purchaseNo||x.transactionNo||x.orderNo||x.advanceNo||x.paymentNo||x.id}</td><td>{x._kind&&x._kind!=='PAYMENT'&&x._kind!=='ADVANCE'?<select value={f[`status_${x.id}`]||x.status} onChange={e=>setF({...f,[`status_${x.id}`]:e.target.value})}><option>{x.status}</option><option>IN_PROGRESS</option><option>READY</option><option>COMPLETED</option><option>CANCELLED</option></select>:<span className="pill">{x.status||'POSTED'}</span>}</td><td>₹{Number(x.total??x.amount??0).toLocaleString('en-IN')}</td><td>{module==='Services'&&<button className="ghost" onClick={()=>updateStatus(x)}>Save status</button>}</td></tr>)}</tbody></Table>{!list.length&&<Empty text={`No ${module.toLowerCase()} records yet.`}/>}</div></div>
}

